import boto3
from pprint import pprint
def lambda_handler(event, context):

    #Connection to Comprehend service
    comprehend = boto3.client("comprehend")
    
    #Parameter that needed to set to trigger the service
    response = comprehend.start_entities_detection_job(
        InputDataConfig={
            'S3Uri': 's3://datahello/NewlyCreated.txt',
    		'InputFormat': 'ONE_DOC_PER_FILE'
	 },
	    OutputDataConfig={
       		'S3Uri': 's3://datahello',
        },
        JobName='ComprehendFYPNew',
        EntityRecognizerArn="arn:aws:comprehend:us-east-1:367639164540:entity-recognizer/intentRecognizer",
        LanguageCode='en',
        DataAccessRoleArn="arn:aws:iam::367639164540:role/service-role/AmazonComprehendServiceRole-entity-recognizer",
        ClientRequestToken='autogenerated'
    )
    
    #JobName=the identifier for the job running
    #EntityRecognizerArn=the unique identifier for the Comprehend recognizer
    #LanguageCode=The language used in the input file
    #DataAccessRoleArn=The role which has the priviledge to carry out the action
    #ClientRequestToken=The token that used to generate the request to the Comprehend services

    pprint(response)
